// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.1
// source: pkg/asset_sub_group/pb/asset_sub_group.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AsgName        string   `protobuf:"bytes,2,opt,name=asg_name,json=asgName,proto3" json:"asg_name,omitempty"`
	AsgParentGroup []string `protobuf:"bytes,3,rep,name=asg_parent_group,json=asgParentGroup,proto3" json:"asg_parent_group,omitempty"`
}

func (x *CreateUpdateRequest) Reset() {
	*x = CreateUpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_asset_sub_group_pb_asset_sub_group_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUpdateRequest) ProtoMessage() {}

func (x *CreateUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_asset_sub_group_pb_asset_sub_group_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUpdateRequest.ProtoReflect.Descriptor instead.
func (*CreateUpdateRequest) Descriptor() ([]byte, []int) {
	return file_pkg_asset_sub_group_pb_asset_sub_group_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUpdateRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateUpdateRequest) GetAsgName() string {
	if x != nil {
		return x.AsgName
	}
	return ""
}

func (x *CreateUpdateRequest) GetAsgParentGroup() []string {
	if x != nil {
		return x.AsgParentGroup
	}
	return nil
}

type CUDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status bool  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Data   *Data `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *CUDResponse) Reset() {
	*x = CUDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_asset_sub_group_pb_asset_sub_group_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CUDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CUDResponse) ProtoMessage() {}

func (x *CUDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_asset_sub_group_pb_asset_sub_group_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CUDResponse.ProtoReflect.Descriptor instead.
func (*CUDResponse) Descriptor() ([]byte, []int) {
	return file_pkg_asset_sub_group_pb_asset_sub_group_proto_rawDescGZIP(), []int{1}
}

func (x *CUDResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *CUDResponse) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Message string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Code    int32    `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	BgpName []string `protobuf:"bytes,4,rep,name=bgp_name,json=bgpName,proto3" json:"bgp_name,omitempty"`
}

func (x *Data) Reset() {
	*x = Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_asset_sub_group_pb_asset_sub_group_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_asset_sub_group_pb_asset_sub_group_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_pkg_asset_sub_group_pb_asset_sub_group_proto_rawDescGZIP(), []int{2}
}

func (x *Data) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Data) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Data) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Data) GetBgpName() []string {
	if x != nil {
		return x.BgpName
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_asset_sub_group_pb_asset_sub_group_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_asset_sub_group_pb_asset_sub_group_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_pkg_asset_sub_group_pb_asset_sub_group_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ReadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Expand  []string `protobuf:"bytes,1,rep,name=expand,proto3" json:"expand,omitempty"`
	PerPage int32    `protobuf:"varint,2,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	Search  string   `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	Sort    string   `protobuf:"bytes,4,opt,name=sort,proto3" json:"sort,omitempty"`
	Page    int32    `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
}

func (x *ReadRequest) Reset() {
	*x = ReadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_asset_sub_group_pb_asset_sub_group_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequest) ProtoMessage() {}

func (x *ReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_asset_sub_group_pb_asset_sub_group_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequest.ProtoReflect.Descriptor instead.
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return file_pkg_asset_sub_group_pb_asset_sub_group_proto_rawDescGZIP(), []int{4}
}

func (x *ReadRequest) GetExpand() []string {
	if x != nil {
		return x.Expand
	}
	return nil
}

func (x *ReadRequest) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

func (x *ReadRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *ReadRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *ReadRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type ReadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool              `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Data    *ReadResponseData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ReadResponse) Reset() {
	*x = ReadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_asset_sub_group_pb_asset_sub_group_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResponse) ProtoMessage() {}

func (x *ReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_asset_sub_group_pb_asset_sub_group_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResponse.ProtoReflect.Descriptor instead.
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return file_pkg_asset_sub_group_pb_asset_sub_group_proto_rawDescGZIP(), []int{5}
}

func (x *ReadResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReadResponse) GetData() *ReadResponseData {
	if x != nil {
		return x.Data
	}
	return nil
}

type ReadResponseData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items  []*AssetSubGroup `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XLinks *Links           `protobuf:"bytes,2,opt,name=_links,json=Links,proto3" json:"_links,omitempty"`
	XMeta  *Meta            `protobuf:"bytes,3,opt,name=_meta,json=Meta,proto3" json:"_meta,omitempty"`
}

func (x *ReadResponseData) Reset() {
	*x = ReadResponseData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_asset_sub_group_pb_asset_sub_group_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadResponseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResponseData) ProtoMessage() {}

func (x *ReadResponseData) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_asset_sub_group_pb_asset_sub_group_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResponseData.ProtoReflect.Descriptor instead.
func (*ReadResponseData) Descriptor() ([]byte, []int) {
	return file_pkg_asset_sub_group_pb_asset_sub_group_proto_rawDescGZIP(), []int{6}
}

func (x *ReadResponseData) GetItems() []*AssetSubGroup {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ReadResponseData) GetXLinks() *Links {
	if x != nil {
		return x.XLinks
	}
	return nil
}

func (x *ReadResponseData) GetXMeta() *Meta {
	if x != nil {
		return x.XMeta
	}
	return nil
}

type Links struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Self  *Link `protobuf:"bytes,1,opt,name=self,proto3" json:"self,omitempty"`
	First *Link `protobuf:"bytes,2,opt,name=first,proto3" json:"first,omitempty"`
	Last  *Link `protobuf:"bytes,3,opt,name=last,proto3" json:"last,omitempty"`
	Next  *Link `protobuf:"bytes,4,opt,name=next,proto3" json:"next,omitempty"`
}

func (x *Links) Reset() {
	*x = Links{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_asset_sub_group_pb_asset_sub_group_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Links) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Links) ProtoMessage() {}

func (x *Links) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_asset_sub_group_pb_asset_sub_group_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Links.ProtoReflect.Descriptor instead.
func (*Links) Descriptor() ([]byte, []int) {
	return file_pkg_asset_sub_group_pb_asset_sub_group_proto_rawDescGZIP(), []int{7}
}

func (x *Links) GetSelf() *Link {
	if x != nil {
		return x.Self
	}
	return nil
}

func (x *Links) GetFirst() *Link {
	if x != nil {
		return x.First
	}
	return nil
}

func (x *Links) GetLast() *Link {
	if x != nil {
		return x.Last
	}
	return nil
}

func (x *Links) GetNext() *Link {
	if x != nil {
		return x.Next
	}
	return nil
}

type Link struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Href string `protobuf:"bytes,1,opt,name=href,proto3" json:"href,omitempty"`
}

func (x *Link) Reset() {
	*x = Link{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_asset_sub_group_pb_asset_sub_group_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Link) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Link) ProtoMessage() {}

func (x *Link) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_asset_sub_group_pb_asset_sub_group_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Link.ProtoReflect.Descriptor instead.
func (*Link) Descriptor() ([]byte, []int) {
	return file_pkg_asset_sub_group_pb_asset_sub_group_proto_rawDescGZIP(), []int{8}
}

func (x *Link) GetHref() string {
	if x != nil {
		return x.Href
	}
	return ""
}

type Meta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalCount  int32 `protobuf:"varint,1,opt,name=totalCount,proto3" json:"totalCount,omitempty"`
	PageCount   int32 `protobuf:"varint,2,opt,name=pageCount,proto3" json:"pageCount,omitempty"`
	CurrentPage int32 `protobuf:"varint,3,opt,name=currentPage,proto3" json:"currentPage,omitempty"`
	PerPage     int32 `protobuf:"varint,4,opt,name=perPage,proto3" json:"perPage,omitempty"`
}

func (x *Meta) Reset() {
	*x = Meta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_asset_sub_group_pb_asset_sub_group_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Meta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Meta) ProtoMessage() {}

func (x *Meta) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_asset_sub_group_pb_asset_sub_group_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Meta.ProtoReflect.Descriptor instead.
func (*Meta) Descriptor() ([]byte, []int) {
	return file_pkg_asset_sub_group_pb_asset_sub_group_proto_rawDescGZIP(), []int{9}
}

func (x *Meta) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *Meta) GetPageCount() int32 {
	if x != nil {
		return x.PageCount
	}
	return 0
}

func (x *Meta) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *Meta) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

type AssetSubGroup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AsgId           int32             `protobuf:"varint,1,opt,name=asg_id,json=asgId,proto3" json:"asg_id,omitempty"`
	AsgName         string            `protobuf:"bytes,2,opt,name=asg_name,json=asgName,proto3" json:"asg_name,omitempty"`
	AsgParentGroup  string            `protobuf:"bytes,3,opt,name=asg_parent_group,json=asgParentGroup,proto3" json:"asg_parent_group,omitempty"`
	AsgOrganization int32             `protobuf:"varint,4,opt,name=asg_organization,json=asgOrganization,proto3" json:"asg_organization,omitempty"`
	AssetGroups     map[string]string `protobuf:"bytes,5,rep,name=assetGroups,proto3" json:"assetGroups,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *AssetSubGroup) Reset() {
	*x = AssetSubGroup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_asset_sub_group_pb_asset_sub_group_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssetSubGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetSubGroup) ProtoMessage() {}

func (x *AssetSubGroup) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_asset_sub_group_pb_asset_sub_group_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetSubGroup.ProtoReflect.Descriptor instead.
func (*AssetSubGroup) Descriptor() ([]byte, []int) {
	return file_pkg_asset_sub_group_pb_asset_sub_group_proto_rawDescGZIP(), []int{10}
}

func (x *AssetSubGroup) GetAsgId() int32 {
	if x != nil {
		return x.AsgId
	}
	return 0
}

func (x *AssetSubGroup) GetAsgName() string {
	if x != nil {
		return x.AsgName
	}
	return ""
}

func (x *AssetSubGroup) GetAsgParentGroup() string {
	if x != nil {
		return x.AsgParentGroup
	}
	return ""
}

func (x *AssetSubGroup) GetAsgOrganization() int32 {
	if x != nil {
		return x.AsgOrganization
	}
	return 0
}

func (x *AssetSubGroup) GetAssetGroups() map[string]string {
	if x != nil {
		return x.AssetGroups
	}
	return nil
}

var File_pkg_asset_sub_group_pb_asset_sub_group_proto protoreflect.FileDescriptor

var file_pkg_asset_sub_group_pb_asset_sub_group_proto_rawDesc = []byte{
	0x0a, 0x2c, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x73, 0x73, 0x65, 0x74, 0x5f, 0x73, 0x75, 0x62, 0x5f,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x2f, 0x70, 0x62, 0x2f, 0x61, 0x73, 0x73, 0x65, 0x74, 0x5f, 0x73,
	0x75, 0x62, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f,
	0x61, 0x73, 0x73, 0x65, 0x74, 0x5f, 0x73, 0x75, 0x62, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x22,
	0x6a, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x73, 0x67, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x73, 0x67, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x28, 0x0a, 0x10, 0x61, 0x73, 0x67, 0x5f, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x5f,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0e, 0x61, 0x73, 0x67,
	0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x22, 0x50, 0x0a, 0x0b, 0x43,
	0x55, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x29, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x15, 0x2e, 0x61, 0x73, 0x73, 0x65, 0x74, 0x5f, 0x73, 0x75, 0x62, 0x5f, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x63, 0x0a,
	0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x62, 0x67, 0x70, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x62, 0x67, 0x70, 0x4e, 0x61,
	0x6d, 0x65, 0x22, 0x1f, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x80, 0x01, 0x0a, 0x0b, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x78, 0x70, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x06, 0x65, 0x78, 0x70, 0x61, 0x6e, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x70,
	0x65, 0x72, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x70,
	0x65, 0x72, 0x50, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x12,
	0x0a, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x6f,
	0x72, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x22, 0x5f, 0x0a, 0x0c, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x12, 0x35, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21,
	0x2e, 0x61, 0x73, 0x73, 0x65, 0x74, 0x5f, 0x73, 0x75, 0x62, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x2e, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0xa3, 0x01, 0x0a, 0x10, 0x52, 0x65, 0x61, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x34, 0x0a, 0x05,
	0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x61, 0x73,
	0x73, 0x65, 0x74, 0x5f, 0x73, 0x75, 0x62, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x41, 0x73,
	0x73, 0x65, 0x74, 0x53, 0x75, 0x62, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x05, 0x69, 0x74, 0x65,
	0x6d, 0x73, 0x12, 0x2d, 0x0a, 0x06, 0x5f, 0x6c, 0x69, 0x6e, 0x6b, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x61, 0x73, 0x73, 0x65, 0x74, 0x5f, 0x73, 0x75, 0x62, 0x5f, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x2e, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x52, 0x05, 0x4c, 0x69, 0x6e, 0x6b,
	0x73, 0x12, 0x2a, 0x0a, 0x05, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x15, 0x2e, 0x61, 0x73, 0x73, 0x65, 0x74, 0x5f, 0x73, 0x75, 0x62, 0x5f, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x04, 0x4d, 0x65, 0x74, 0x61, 0x22, 0xb5, 0x01,
	0x0a, 0x05, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x12, 0x29, 0x0a, 0x04, 0x73, 0x65, 0x6c, 0x66, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x61, 0x73, 0x73, 0x65, 0x74, 0x5f, 0x73, 0x75,
	0x62, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x04, 0x73, 0x65,
	0x6c, 0x66, 0x12, 0x2b, 0x0a, 0x05, 0x66, 0x69, 0x72, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x61, 0x73, 0x73, 0x65, 0x74, 0x5f, 0x73, 0x75, 0x62, 0x5f, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x2e, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x05, 0x66, 0x69, 0x72, 0x73, 0x74, 0x12,
	0x29, 0x0a, 0x04, 0x6c, 0x61, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e,
	0x61, 0x73, 0x73, 0x65, 0x74, 0x5f, 0x73, 0x75, 0x62, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e,
	0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x04, 0x6c, 0x61, 0x73, 0x74, 0x12, 0x29, 0x0a, 0x04, 0x6e, 0x65,
	0x78, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x61, 0x73, 0x73, 0x65, 0x74,
	0x5f, 0x73, 0x75, 0x62, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x4c, 0x69, 0x6e, 0x6b, 0x52,
	0x04, 0x6e, 0x65, 0x78, 0x74, 0x22, 0x1a, 0x0a, 0x04, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x12, 0x0a,
	0x04, 0x68, 0x72, 0x65, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x72, 0x65,
	0x66, 0x22, 0x80, 0x01, 0x0a, 0x04, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x61,
	0x67, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x70,
	0x61, 0x67, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x75, 0x72, 0x72,
	0x65, 0x6e, 0x74, 0x50, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x63,
	0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x50, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x65,
	0x72, 0x50, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x70, 0x65, 0x72,
	0x50, 0x61, 0x67, 0x65, 0x22, 0xa9, 0x02, 0x0a, 0x0d, 0x41, 0x73, 0x73, 0x65, 0x74, 0x53, 0x75,
	0x62, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x15, 0x0a, 0x06, 0x61, 0x73, 0x67, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x61, 0x73, 0x67, 0x49, 0x64, 0x12, 0x19, 0x0a,
	0x08, 0x61, 0x73, 0x67, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x61, 0x73, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x28, 0x0a, 0x10, 0x61, 0x73, 0x67, 0x5f,
	0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0e, 0x61, 0x73, 0x67, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x12, 0x29, 0x0a, 0x10, 0x61, 0x73, 0x67, 0x5f, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69,
	0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x61, 0x73,
	0x67, 0x4f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x51, 0x0a,
	0x0b, 0x61, 0x73, 0x73, 0x65, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x18, 0x05, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x61, 0x73, 0x73, 0x65, 0x74, 0x5f, 0x73, 0x75, 0x62, 0x5f, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x2e, 0x41, 0x73, 0x73, 0x65, 0x74, 0x53, 0x75, 0x62, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x2e, 0x41, 0x73, 0x73, 0x65, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x0b, 0x61, 0x73, 0x73, 0x65, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73,
	0x1a, 0x3e, 0x0a, 0x10, 0x41, 0x73, 0x73, 0x65, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01,
	0x32, 0xbf, 0x02, 0x0a, 0x14, 0x41, 0x73, 0x73, 0x65, 0x74, 0x53, 0x75, 0x62, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4c, 0x0a, 0x06, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x12, 0x24, 0x2e, 0x61, 0x73, 0x73, 0x65, 0x74, 0x5f, 0x73, 0x75, 0x62, 0x5f,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x61, 0x73, 0x73, 0x65,
	0x74, 0x5f, 0x73, 0x75, 0x62, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x43, 0x55, 0x44, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4c, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x12, 0x24, 0x2e, 0x61, 0x73, 0x73, 0x65, 0x74, 0x5f, 0x73, 0x75, 0x62, 0x5f, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x61, 0x73, 0x73, 0x65, 0x74, 0x5f,
	0x73, 0x75, 0x62, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x43, 0x55, 0x44, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x46, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12,
	0x1e, 0x2e, 0x61, 0x73, 0x73, 0x65, 0x74, 0x5f, 0x73, 0x75, 0x62, 0x5f, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1c, 0x2e, 0x61, 0x73, 0x73, 0x65, 0x74, 0x5f, 0x73, 0x75, 0x62, 0x5f, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x2e, 0x43, 0x55, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43, 0x0a,
	0x04, 0x52, 0x65, 0x61, 0x64, 0x12, 0x1c, 0x2e, 0x61, 0x73, 0x73, 0x65, 0x74, 0x5f, 0x73, 0x75,
	0x62, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x61, 0x73, 0x73, 0x65, 0x74, 0x5f, 0x73, 0x75, 0x62, 0x5f,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x1a, 0x5a, 0x18, 0x2e, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x73, 0x73, 0x65,
	0x74, 0x5f, 0x73, 0x75, 0x62, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2f, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_asset_sub_group_pb_asset_sub_group_proto_rawDescOnce sync.Once
	file_pkg_asset_sub_group_pb_asset_sub_group_proto_rawDescData = file_pkg_asset_sub_group_pb_asset_sub_group_proto_rawDesc
)

func file_pkg_asset_sub_group_pb_asset_sub_group_proto_rawDescGZIP() []byte {
	file_pkg_asset_sub_group_pb_asset_sub_group_proto_rawDescOnce.Do(func() {
		file_pkg_asset_sub_group_pb_asset_sub_group_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_asset_sub_group_pb_asset_sub_group_proto_rawDescData)
	})
	return file_pkg_asset_sub_group_pb_asset_sub_group_proto_rawDescData
}

var file_pkg_asset_sub_group_pb_asset_sub_group_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_pkg_asset_sub_group_pb_asset_sub_group_proto_goTypes = []interface{}{
	(*CreateUpdateRequest)(nil), // 0: asset_sub_group.CreateUpdateRequest
	(*CUDResponse)(nil),         // 1: asset_sub_group.CUDResponse
	(*Data)(nil),                // 2: asset_sub_group.Data
	(*DeleteRequest)(nil),       // 3: asset_sub_group.DeleteRequest
	(*ReadRequest)(nil),         // 4: asset_sub_group.ReadRequest
	(*ReadResponse)(nil),        // 5: asset_sub_group.ReadResponse
	(*ReadResponseData)(nil),    // 6: asset_sub_group.ReadResponseData
	(*Links)(nil),               // 7: asset_sub_group.Links
	(*Link)(nil),                // 8: asset_sub_group.Link
	(*Meta)(nil),                // 9: asset_sub_group.Meta
	(*AssetSubGroup)(nil),       // 10: asset_sub_group.AssetSubGroup
	nil,                         // 11: asset_sub_group.AssetSubGroup.AssetGroupsEntry
}
var file_pkg_asset_sub_group_pb_asset_sub_group_proto_depIdxs = []int32{
	2,  // 0: asset_sub_group.CUDResponse.data:type_name -> asset_sub_group.Data
	6,  // 1: asset_sub_group.ReadResponse.data:type_name -> asset_sub_group.ReadResponseData
	10, // 2: asset_sub_group.ReadResponseData.items:type_name -> asset_sub_group.AssetSubGroup
	7,  // 3: asset_sub_group.ReadResponseData._links:type_name -> asset_sub_group.Links
	9,  // 4: asset_sub_group.ReadResponseData._meta:type_name -> asset_sub_group.Meta
	8,  // 5: asset_sub_group.Links.self:type_name -> asset_sub_group.Link
	8,  // 6: asset_sub_group.Links.first:type_name -> asset_sub_group.Link
	8,  // 7: asset_sub_group.Links.last:type_name -> asset_sub_group.Link
	8,  // 8: asset_sub_group.Links.next:type_name -> asset_sub_group.Link
	11, // 9: asset_sub_group.AssetSubGroup.assetGroups:type_name -> asset_sub_group.AssetSubGroup.AssetGroupsEntry
	0,  // 10: asset_sub_group.AssetSubGroupService.Create:input_type -> asset_sub_group.CreateUpdateRequest
	0,  // 11: asset_sub_group.AssetSubGroupService.Update:input_type -> asset_sub_group.CreateUpdateRequest
	3,  // 12: asset_sub_group.AssetSubGroupService.Delete:input_type -> asset_sub_group.DeleteRequest
	4,  // 13: asset_sub_group.AssetSubGroupService.Read:input_type -> asset_sub_group.ReadRequest
	1,  // 14: asset_sub_group.AssetSubGroupService.Create:output_type -> asset_sub_group.CUDResponse
	1,  // 15: asset_sub_group.AssetSubGroupService.Update:output_type -> asset_sub_group.CUDResponse
	1,  // 16: asset_sub_group.AssetSubGroupService.Delete:output_type -> asset_sub_group.CUDResponse
	5,  // 17: asset_sub_group.AssetSubGroupService.Read:output_type -> asset_sub_group.ReadResponse
	14, // [14:18] is the sub-list for method output_type
	10, // [10:14] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_pkg_asset_sub_group_pb_asset_sub_group_proto_init() }
func file_pkg_asset_sub_group_pb_asset_sub_group_proto_init() {
	if File_pkg_asset_sub_group_pb_asset_sub_group_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_asset_sub_group_pb_asset_sub_group_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateUpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_asset_sub_group_pb_asset_sub_group_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CUDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_asset_sub_group_pb_asset_sub_group_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_asset_sub_group_pb_asset_sub_group_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_asset_sub_group_pb_asset_sub_group_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_asset_sub_group_pb_asset_sub_group_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_asset_sub_group_pb_asset_sub_group_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadResponseData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_asset_sub_group_pb_asset_sub_group_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Links); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_asset_sub_group_pb_asset_sub_group_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Link); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_asset_sub_group_pb_asset_sub_group_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Meta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_asset_sub_group_pb_asset_sub_group_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AssetSubGroup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_asset_sub_group_pb_asset_sub_group_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_asset_sub_group_pb_asset_sub_group_proto_goTypes,
		DependencyIndexes: file_pkg_asset_sub_group_pb_asset_sub_group_proto_depIdxs,
		MessageInfos:      file_pkg_asset_sub_group_pb_asset_sub_group_proto_msgTypes,
	}.Build()
	File_pkg_asset_sub_group_pb_asset_sub_group_proto = out.File
	file_pkg_asset_sub_group_pb_asset_sub_group_proto_rawDesc = nil
	file_pkg_asset_sub_group_pb_asset_sub_group_proto_goTypes = nil
	file_pkg_asset_sub_group_pb_asset_sub_group_proto_depIdxs = nil
}
