// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.1
// source: pkg/asset_group/pb/asset_group.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AssetGroupService_Create_FullMethodName = "/asset_group.AssetGroupService/Create"
	AssetGroupService_Update_FullMethodName = "/asset_group.AssetGroupService/Update"
	AssetGroupService_Delete_FullMethodName = "/asset_group.AssetGroupService/Delete"
	AssetGroupService_Read_FullMethodName   = "/asset_group.AssetGroupService/Read"
)

// AssetGroupServiceClient is the client API for AssetGroupService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AssetGroupServiceClient interface {
	Create(ctx context.Context, in *CreateUpdateRequest, opts ...grpc.CallOption) (*CUDResponse, error)
	Update(ctx context.Context, in *CreateUpdateRequest, opts ...grpc.CallOption) (*CUDResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*CUDResponse, error)
	Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error)
}

type assetGroupServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAssetGroupServiceClient(cc grpc.ClientConnInterface) AssetGroupServiceClient {
	return &assetGroupServiceClient{cc}
}

func (c *assetGroupServiceClient) Create(ctx context.Context, in *CreateUpdateRequest, opts ...grpc.CallOption) (*CUDResponse, error) {
	out := new(CUDResponse)
	err := c.cc.Invoke(ctx, AssetGroupService_Create_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetGroupServiceClient) Update(ctx context.Context, in *CreateUpdateRequest, opts ...grpc.CallOption) (*CUDResponse, error) {
	out := new(CUDResponse)
	err := c.cc.Invoke(ctx, AssetGroupService_Update_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetGroupServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*CUDResponse, error) {
	out := new(CUDResponse)
	err := c.cc.Invoke(ctx, AssetGroupService_Delete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetGroupServiceClient) Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error) {
	out := new(ReadResponse)
	err := c.cc.Invoke(ctx, AssetGroupService_Read_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AssetGroupServiceServer is the server API for AssetGroupService service.
// All implementations must embed UnimplementedAssetGroupServiceServer
// for forward compatibility
type AssetGroupServiceServer interface {
	Create(context.Context, *CreateUpdateRequest) (*CUDResponse, error)
	Update(context.Context, *CreateUpdateRequest) (*CUDResponse, error)
	Delete(context.Context, *DeleteRequest) (*CUDResponse, error)
	Read(context.Context, *ReadRequest) (*ReadResponse, error)
	mustEmbedUnimplementedAssetGroupServiceServer()
}

// UnimplementedAssetGroupServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAssetGroupServiceServer struct {
}

func (UnimplementedAssetGroupServiceServer) Create(context.Context, *CreateUpdateRequest) (*CUDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedAssetGroupServiceServer) Update(context.Context, *CreateUpdateRequest) (*CUDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedAssetGroupServiceServer) Delete(context.Context, *DeleteRequest) (*CUDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedAssetGroupServiceServer) Read(context.Context, *ReadRequest) (*ReadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Read not implemented")
}
func (UnimplementedAssetGroupServiceServer) mustEmbedUnimplementedAssetGroupServiceServer() {}

// UnsafeAssetGroupServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AssetGroupServiceServer will
// result in compilation errors.
type UnsafeAssetGroupServiceServer interface {
	mustEmbedUnimplementedAssetGroupServiceServer()
}

func RegisterAssetGroupServiceServer(s grpc.ServiceRegistrar, srv AssetGroupServiceServer) {
	s.RegisterService(&AssetGroupService_ServiceDesc, srv)
}

func _AssetGroupService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetGroupServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetGroupService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetGroupServiceServer).Create(ctx, req.(*CreateUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetGroupService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetGroupServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetGroupService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetGroupServiceServer).Update(ctx, req.(*CreateUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetGroupService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetGroupServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetGroupService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetGroupServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetGroupService_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetGroupServiceServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetGroupService_Read_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetGroupServiceServer).Read(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AssetGroupService_ServiceDesc is the grpc.ServiceDesc for AssetGroupService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AssetGroupService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "asset_group.AssetGroupService",
	HandlerType: (*AssetGroupServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _AssetGroupService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _AssetGroupService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _AssetGroupService_Delete_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _AssetGroupService_Read_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/asset_group/pb/asset_group.proto",
}
